In [0]:
from google.colab import files
files.upload()

Saving file.csv to file.csv


{'file.csv': b'age income student credit-rating result \r\nyouth high no fair no \r\nyouth high no excellent no \r\nmiddle high no fair yes \r\nsenior medium no fair yes \r\nsenior low yes fair yes \r\nsenior low yes excellent no \r\nmiddle low yes excellent yes \r\nyouth medium no fair no \r\nyouth low yes fair yes \r\nsenior medium yes fair yes \r\nyouth medium yes excellent yes \r\nmiddle medium no excellent yes \r\nmiddle high yes fair yes \r\nsenior medium no excellent no \r\n'}

In [0]:
import pandas as pd
import numpy as np
df = pd.read_csv('file2.csv', header=0, delim_whitespace=True)

In [0]:
mainTab=np.zeros(df.shape,dtype="uint8")

for i in range(df.shape[1]) :
    mainTab[:,i] = turnIntoNumbers(list(df.iloc[:,i]))

In [0]:
def turnIntoNumbers(myList) :
    key=list(set(myList))
    #print(key)
    newList=[]
    for i in range(len(myList)) :
        newList.append(key.index(myList[i]))
    return newList

In [0]:
class TreeNode :
    def __init__(self,matrix,keyColumn):
        self.table=matrix
        self.children=[]
        self.keyColumn=keyColumn

In [0]:
import copy
root=TreeNode(mainTab,None)

NodesToProcess=[root]

countingIterations=0
while len(NodesToProcess) != 0 :
    
    countingIterations+=1
    print("Iteration ",countingIterations)
    print(NodesToProcess[0].table)
        
    chosen=chooseColumn(NodesToProcess[0].table)
    
    if chosen == None :
        #print("Done")
        del NodesToProcess[0]
        continue
    #print(chosen)
    childData=list(set(NodesToProcess[0].table[:,chosen]))
    
    myDict={i:list(NodesToProcess[0].table[:,chosen]).count(i) for i in childData}
    
    divTabs=[]
    
    for i in myDict.keys() :
        newArray=np.zeros((myDict[i],df.shape[1]),dtype='uint8')
        divTabs.append(newArray)
    
    divTabs=np.array(divTabs)
    tabIndexes={}
    
    #print(tabIndexes)
    
    newTab=NodesToProcess[0].table
    #print(newTab.shape)
    for i in range(newTab.shape[0]) :
        t=newTab[i,chosen]
        divTabs[childData.index(t)][tabIndexes.get(t,0)]=newTab[i]
        tabIndexes[t]=tabIndexes.get(t,0)+1
        
    #print(divTabs)
    for i in range(len(childData)) :
        newObj=TreeNode(divTabs[i],chosen)
        print("Div tab is ")
        print(divTabs[i])
        print("Chosen is ",chosen)
        NodesToProcess[0].children.append(newObj)
        NodesToProcess.append(newObj)
        
        
    del NodesToProcess[0]
    

Iteration  1
[[1 2 1 0 1]
 [1 2 1 1 1]
 [2 2 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [2 0 0 1 0]
 [1 1 1 0 1]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 1 0 1 0]
 [2 1 1 1 0]
 [2 2 0 0 0]
 [0 1 1 1 1]]
Div tab is 
[[0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [0 1 1 1 1]]
Chosen is  0
Div tab is 
[[1 2 1 0 1]
 [1 2 1 1 1]
 [1 1 1 0 1]
 [1 0 0 0 0]
 [1 1 0 1 0]]
Chosen is  0
Div tab is 
[[2 2 1 0 0]
 [2 0 0 1 0]
 [2 1 1 1 0]
 [2 2 0 0 0]]
Chosen is  0
Iteration  2
[[0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [0 1 0 0 0]
 [0 1 1 1 1]]
Div tab is 
[[0 1 1 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]]
Chosen is  3
Div tab is 
[[0 0 0 1 1]
 [0 1 1 1 1]]
Chosen is  3
Iteration  3
[[1 2 1 0 1]
 [1 2 1 1 1]
 [1 1 1 0 1]
 [1 0 0 0 0]
 [1 1 0 1 0]]
Div tab is 
[[1 0 0 0 0]
 [1 1 0 1 0]]
Chosen is  2
Div tab is 
[[1 2 1 0 1]
 [1 2 1 1 1]
 [1 1 1 0 1]]
Chosen is  2
Iteration  4
[[2 2 1 0 0]
 [2 0 0 1 0]
 [2 1 1 1 0]
 [2 2 0 0 0]]
Iteration  5
[[0 1 1 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]]
Iteration  6
[[0 0 0 1 1]
 [0 1 1

In [0]:
import math
def entropy(newList) :

    myDict1={i:list(newList).count(i) for i in set(newList)}
    #print(myDict)
    Entropy=0
    for i in myDict1.keys() :
        Entropy+=-(myDict1[i]/len(newList))*((math.log10(myDict1[i]/len(newList))/math.log10(2)))
        
    #print("Entropy",Entropy)
    return Entropy

def chooseColumn(matrix) :
    
    #print(matrix)
    newList=matrix[:,matrix.shape[1]-1]
    if len(set(newList)) == 1 :
        #print("done")
        return None
    
    info=entropy(newList)
    #print(len(newList))
    #print("The Entropy is ",info)
    columnVals=[]
    for i in range(matrix.shape[1]-1) :
        #print("Attribute ",list(df)[i])
        #print(matrix[:,i])
        myDict={j:(list(matrix[:,i]).count(j)) for j in list(set(matrix[:,i]))}
        #print(myDict)
        #print(list(set(matrix[:,i])))
        #print(list(matrix[:,i]).count(2))
        if len(myDict) == 1 :
            columnVals.append(float('-inf'))
            continue
        
        infoAttr=0
        for j in myDict.keys() :
            temp=myDict[j]/matrix.shape[0]
            #print("The divsion is ",myDict[j],end="/")
            #print(matrix.shape[0])
            newList=[]
            for k in range(matrix.shape[0]) :
                if matrix[k,i] == j :
                    newList.append(matrix[k][matrix.shape[1]-1])
            
            #print(newList)
            mul=entropy(newList)
            #print("The mulitplication Entropy is ",mul)
            temp*=mul
            #print("Particular",temp)
            infoAttr+=-temp
        #print("End")
        #print("Gain of ",list(df)[i],end=" ")
        #print(info+infoAttr)
        columnVals.append(info+infoAttr)
    
    #print(columnVals)
    return(np.argmax(columnVals))
    
#chooseColumn(mainTab)
#print(mainTab.shape)

In [0]:
def printingTab(obj,myStr) :
    #print(obj.keyColumn,end=",")
    if obj.keyColumn == None :
            myStr+="OrigTab"
    else :
        myStr+=str(obj.keyColumn)
        myStr+=","
    if obj.keyColumn!=None :
        #print(obj.table[0][obj.keyColumn],end=" ")
        myStr+=str(obj.table[0][obj.keyColumn])
        myStr+=" "
    #print(" --> ",end=" ")
    myStr+=" --> "
    if len(obj.children) == 0 :
        #print(obj.table[0][obj.table.shape[1]-1])
        myStr+=str(obj.table[0][obj.table.shape[1]-1])
        print(myStr)
        return
    
    for i in obj.children :
            printingTab(i,myStr)
        
    
printingTab(root," ")

 OrigTab --> 0,0  --> 3,0  --> 0
 OrigTab --> 0,0  --> 3,1  --> 1
 OrigTab --> 0,1  --> 2,0  --> 0
 OrigTab --> 0,1  --> 2,1  --> 1
 OrigTab --> 0,2  --> 0


In [0]:
print(root.children[0].children[0].keyColumn)

3
